# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('user_name', models.CharField(db_index=True, max_length=64)),
                ('group_name', models.CharField(max_length=128)),
                ('calling_station_id', models.CharField(blank=True, max_length=128)),
                ('acct_status_type', models.CharField(blank=True, max_length=128)),
                ('acct_session_id', models.CharField(blank=True, max_length=128)),
                ('acct_session_time', models.IntegerField(blank=True)),
                ('service_type', models.CharField(max_length=128)),
                ('framed_protocol', models.CharField(max_length=128)),
                ('acct_input_octets', models.IntegerField(blank=True)),
                ('acct_output_octets', models.IntegerField(blank=True)),
                ('acct_input_packets', models.IntegerField(blank=True)),
                ('acct_output_packets', models.IntegerField(blank=True)),
                ('framed_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('nas_port', models.IntegerField(blank=True)),
                ('nas_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cisco_av_pair', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ACSLogF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acs_log_file', models.CharField(max_length=128, unique=True)),
                ('acs_log_data', models.DateField(db_index=True, default=None)),
            ],
            options={
                'ordering': ['-acs_log_data'],
            },
        ),
        migrations.AddField(
            model_name='acslog',
            name='acs_log_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acs_logs.ACSLogF'),
        ),
    ]
