# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acslog',
            name='acct_input_octets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_input_packets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_output_octets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_output_packets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='cisco_av_pair',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='nas_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
