# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_logs', '0002_auto_20170814_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acslog',
            name='cisco_av_pair',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='framed_protocol',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='service_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
