# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_logs', '0003_auto_20170814_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acslog',
            name='acct_input_octets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_input_packets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_output_octets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_output_packets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_session_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='nas_port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
