# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_logs', '0004_auto_20170814_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acslog',
            name='acct_input_packets',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='acct_output_packets',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='acct_session_id',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='calling_station_id',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='cisco_av_pair',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='framed_ip_address',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='framed_protocol',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='nas_ip_address',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='nas_port',
        ),
        migrations.RemoveField(
            model_name='acslog',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_session_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_status_type',
            field=models.CharField(max_length=128),
        ),
    ]
