# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_logs', '0005_auto_20170815_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acslog',
            name='acct_input_octets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_output_octets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
