# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_logs', '0008_auto_20170815_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acslog',
            name='acct_input_octets',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='acslog',
            name='acct_output_octets',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
